version: "3"

services:
    php-fpm:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./:/var/www

    nginx:
        build:
            context: ./docker/nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php-fpm

    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_DATABASE=deployer
            - MYSQL_USER=deployer
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - ./docker/database/data.sql:/docker-entrypoint-initdb.d/data.sql